sudo: required

language: c

env:
  global:
    # for the latest public release
    # - GAPCONTAINER="gapsystem/gap-docker"
    # - GAPDIRNAME="gap4r8"
    # for the tests of the stable-4.8 branch
    # - GAPCONTAINER="gapsystem/gap-docker-stable"
    # - GAPDIRNAME="gap-stable-4.8"
    # for the tests of the master branch
    - GAPCONTAINER="gapsystem/gap-docker-master"
    - GAPDIRNAME="gap-master"

  matrix:
    - PKG_NAME=curlInterface
    - PKG_NAME=datastructures
    - PKG_NAME=Digraphs
    - PKG_NAME=example
    - PKG_NAME=IO
    - PKG_NAME=JupyterKernel
    - PKG_NAME=Memoisation
    - PKG_NAME=openmath
    - PKG_NAME=permut
    - PKG_NAME=Semigroups
    - PKG_NAME=ZeroMQInterface
    - PKG_NAME=YangBaxter

services:
  - docker

before_install:
- docker pull ${GAPCONTAINER}

script:
    - docker version
    - docker run -v $PWD:/home/gap/travis/ ${GAPCONTAINER} /bin/sh -c "GAPDIRNAME=${GAPDIRNAME} PKG_NAME=${PKG_NAME} TERM=xterm LANG=en_GB.UTF-8 /home/gap/travis/ci.sh"
